version : "3"
services:
  springBootApp:
    image: sudiptapahari/user-service:1.0
    container_name: docker-postgres-springboot-demo-app
    environment:
      - POSTGRES_HOST=docker-postgres-springboot-demo-db
    ports:
      - "8081:8085"
    networks:
      - network
    depends_on:
      - postgresDb
    restart : unless-stopped

  postgresDb:
    image: postgres:13.2
    container_name: docker-postgres-springboot-demo-db
    ports:
      - "5432:5432"
    networks:
     - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Destroyer@21
      - POSTGRES_DB=CaseStudy
networks:
  network:
volumes:
  volume:
